### PR TITLE
Update MiMa to 0.8.1

### PR DESCRIPTION
**Pull request by sideeffffect**
/cc @sjrd

### CODE REVIEW

**Comment by SethTisue** [comment]
(consider enabling Scala Steward in this repo?)

**Review by sjrd — APPROVED** [review]

**Comment by sjrd** [comment]
> (consider enabling Scala Steward in this repo?)

No thanks. I'm not a fan of Scala Steward for the repos I maintain. I build stuff to be compatible forever. I don't need to upgrade to every new shiny thing every two weeks. I upgrade when I need to upgrade. It's great that many people love it. It's just not for me.

**Comment by sideeffffect** [comment]
Thanks for merging @sjrd :smiley:  Would you be open to other improvements (besides Steward), like migrating to GitHub Actions, Scalafmt and such?

**Comment by sjrd** [comment]
I have migrated to GitHub Actions myself, because it is basically impossible to actually run the CI through a PR first.

scalafmt is problematic. We still can't enable it in the Scala.js repo because its support for binpacking is broken and the maintainers are not interested in fixing it. This is OK; it just means we keep formatting things manually. Since this repo is much smaller, there is a chance that it could be configured with binpacking in a way that does not trigger any of the scalafmt binpacking bugs. If you want to try your luck, feel free. Our coding style guide is at https://github.com/scala-js/scala-js/blob/master/CODINGSTYLE.md.

**Pull request merged**
